services:
  - type: web
    name: modura-storefront
    env: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: MEDUSA_BACKEND_URL
        sync: false
      - key: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_DEFAULT_REGION
        value: "be"
      - key: NEXT_PUBLIC_STRIPE_KEY
        sync: false
      - key: REVALIDATE_SECRET
        generateValue: true